version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-conda:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          key: conda
      - run:
         command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
            source "$HOME/miniconda/etc/profile.d/conda.sh"
            conda config --set always_yes yes
            conda update conda
            sed -i "s/python>=[0-9]\.[0-9]/python=${TRAVIS_PYTHON_VERSION}/g" requirements/environment.yml
            sed -i '/mpi4py/d' requirements/environment.yml
            conda env create -f requirements/environment.yml
            conda activate elephant
            pip install -r requirements/requirements-tests.txt
            pip install coverage coveralls
         name: conda requirements cached
      - python/save-cache:
          key: conda
      - run:
          command: |
            python setup.py install
            python -c "from elephant.spade import HAVE_FIM; assert HAVE_FIM"
            pip list
            pip -V
            python --version
          name: install elephant package
      - run: pip install coveralls nose
      - run:
          command: |
            nosetests --with-coverage --cover-package=elephant
            coveralls
          name: Test & coverage

  build-pip:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          key: pip
      - run:
          command: |
            pip install -r requirements/requirements.txt
            pip install -r requirements/requirements-tests.txt
            pip install coverage coveralls
          name: pip requirements cached
      - python/save-cache:
          key: pip
      - run:
          command: |
            python setup.py install
            python -c "from elephant.spade import HAVE_FIM; assert HAVE_FIM"
            pip list
            pip -V
            python --version
          name: install elephant package
      - run:
          command: |
            nosetests elephant/test/test_asset.py
            nosetests elephant/test/test_causality.py
            nosetests elephant/test/test_cell_assembly_detection.py
            nosetests elephant/test/test_change_point_detection.py
            nosetests elephant/test/test_conversion.py
            nosetests elephant/test/test_csd.py
            nosetests elephant/test/test_cubic.py
            nosetests elephant/test/test_gpfa.py
            nosetests elephant/test/test_icsd.py
            nosetests elephant/test/test_kcsd.py
            nosetests elephant/test/test_kernels.py
            nosetests elephant/test/test_neo_tools.py
            nosetests elephant/test/test_pandas_bridge.py
            nosetests elephant/test/test_parallel.py
            nosetests elephant/test/test_phase_analysis.py
            nosetests elephant/test/test_signal_processing.py
            nosetests elephant/test/test_spade.py
            nosetests elephant/test/test_spectral.py
            nosetests elephant/test/test_spike_train_correlation.py
            nosetests elephant/test/test_spike_train_dissimilarity.py
            nosetests elephant/test/test_spike_train_generation.py
            nosetests elephant/test/test_spike_train_surrogates.py
            nosetests elephant/test/test_spike_train_synchrony.py
            nosetests elephant/test/test_sta.py
            nosetests elephant/test/test_statistics.py
            nosetests elephant/test/test_unitary_event_analysis.py
            nosetests elephant/test/test_utils.py
            nosetests elephant/test/test_waveform_features.py
          name: nosetests

workflows:
  main:
    jobs:
      - build-pip
